[project]
name = "tuleap-documentation-fr"
version = "0.0.0"
description = ""
authors = [{ name = "Enalean team" }]
requires-python = ">=3.13"
dependencies = [
    "Sphinx>=9.1,<10",
    "sphinx-rtd-theme>=3.0.2,<4",
    "sphinxcontrib-jquery>=4.1,<5",
]

[tool.setuptools]
py-modules = []
